name: GitHub Pages

on:
  push:
    branches:
      - main  # Changez ceci si votre branche principale est différente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'  # Spécifiez la version Ruby si nécessaire

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install  # Installe les dépendances définies dans Gemfile

      - name: Build the site
        run: |
          bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./_site
